### ISSUE TITLE
Error initiating gophercloud cinder client: No suitable endpoint

### ISSUE THREAD

**Issue by olivibernard** [j-griffith/cinder-docker-driver#3]
Hi,

I get an error with the command 
```
$ sudo service cinder-docker-driver status
Nov 14 15:54:18 beats cinder-docker-driver[3752]: time="2016-11-14T15:54:18+01:00" level=info msg="Set InitiatorIFace to: default"
Nov 14 15:54:18 beats cinder-docker-driver[3752]: time="2016-11-14T15:54:18+01:00" level=info msg="Set node InitiatorIP to: "
Nov 14 15:54:18 beats cinder-docker-driver[3752]: time="2016-11-14T15:54:18+01:00" level=info msg="Set DefaultVolSz to: 1 GiB"
Nov 14 15:54:18 beats cinder-docker-driver[3752]: time="2016-11-14T15:54:18+01:00" level=info msg="Set Endpoint to: http://openstack.mydomain.com:5000/v2.0"
Nov 14 15:54:18 beats cinder-docker-driver[3752]: time="2016-11-14T15:54:18+01:00" level=info msg="Set Username to: test_account"
Nov 14 15:54:18 beats cinder-docker-driver[3752]: time="2016-11-14T15:54:18+01:00" level=info msg="Set TenantID to: 3xxxxxxxxxxxxxxxxxxxxxxxxxxxxf"
Nov 14 15:54:18 beats cinder-docker-driver[3752]: time="2016-11-14T15:54:18+01:00" level=fatal msg="Error initiating gophercloud cinder client: No suitable endpoint
```

[This doc](https://godoc.org/github.com/rackspace/gophercloud) explains 
_ErrServiceNotFound is returned when no service in a service catalog matches
    // the provided EndpointOpts. This is generally returned by provider service
    // factory methods like "NewComputeV2()" and can mean that a service is not
    // enabled for your account._

So I tried this
```
$ curl -L -u test_account:not_my_password http://openstack.mydomain.com:5000/v2.0 
{"version": {"status": "stable", "updated": "2014-04-17T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v2.0+json"}], "id": "v2.0", "links": [{"href": "http://openstack.mydomain.com:5000/v2.0/", "rel": "self"}, {"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}]}}
```

It seems that the endpoint is reachable.
My openstack admin told me to use API V3, with https, something like 
https://openstack.mydomain.com:5000/v3

I setted up the certs, and reload/restarted cinder-docker-driver.
The error concerns now a missing domainName or domainID 
```
Nov 14 16:34:08 beats cinder-docker-driver[6625]: time="2016-11-14T16:34:08+01:00" level=info msg="Set InitiatorIFace to: default"
Nov 14 16:34:08 beats cinder-docker-driver[6625]: time="2016-11-14T16:34:08+01:00" level=info msg="Set node InitiatorIP to: "
Nov 14 16:34:08 beats cinder-docker-driver[6625]: time="2016-11-14T16:34:08+01:00" level=info msg="Set DefaultVolSz to: 1 GiB"
Nov 14 16:34:08 beats cinder-docker-driver[6625]: time="2016-11-14T16:34:08+01:00" level=info msg="Set Endpoint to: https://openstack.mydomain.com:5000/v3"
Nov 14 16:34:08 beats cinder-docker-driver[6625]: time="2016-11-14T16:34:08+01:00" level=info msg="Set Username to: test_account"
Nov 14 16:34:08 beats cinder-docker-driver[6625]: time="2016-11-14T16:34:08+01:00" level=info msg="Set TenantID to: 3xxxxxxxxxxxxxxxxxxxxxxxxxxxxf"
Nov 14 16:34:08 beats cinder-docker-driver[6625]: time="2016-11-14T16:34:08+01:00" level=fatal msg="Error initiating gophercloud provider client: You must provide exactly one of DomainID or DomainName to authenticate by Username"
Nov 14 16:34:08 beats systemd[1]: cinder-docker-driver.service: Main process exited, code=exited, status=1/FAILURE
Nov 14 16:34:08 beats systemd[1]: cinder-docker-driver.service: Unit entered failed state.
Nov 14 16:34:08 beats systemd[1]: cinder-docker-driver.service: Failed with result 'exit-code'.
```

The github exemple shows only API V2. 
Does cinder-docker-driver works with openstack API V3 ?
If yes, could you please provide a config.json exemple to do it in V3 ?

I tried to add DomainName option in config.json file, but it wat still the same error.
(Ref : https://godoc.org/github.com/rackspace/gophercloud#AuthOptions)

Thanks !

**Comment by j-griffith** [comment]
Hi olivibernard, thanks for pointing this out.  So you should still be able to access the V2 Identity endpoint; but regardless.  You're correct, you need to specify the DomainName or DomainID in the config file for V3 support, BUT I don't have the mechansim implemented in the driver itself.

It's pretty easy to add it, I'll see if I can add it real quick tonight.

Thanks!

**Comment by olivibernard** [comment]
Hello

Do you have any news about V3 ?
Your plugin looks really fantastic and I need it.

Please do not hesitate to contact me for testing.

Thanks !

**Comment by j-griffith** [comment]
Hi Olivibernard, sorry I forgot about this.  I've uploaded a quick fix here:

https://github.com/j-griffith/cinder-docker-driver/commit/c32143e8046d900f737a14278288d983a43099bf

Give it a try, note that I haven't built/uploaded a new binary/release for this yet so you'll need to pull the source and build it yourself.  I'll get some testing done and release a new build later today depending on your feedback.

Thanks!

**Comment by olivibernard** [comment]
Hi j-griffith

Thanks a lot for this fix. 
I will try it next monday and come back soon.

**Comment by olivibernard** [comment]
Hi j-griffith

Could you please tell me if cinder-docker-driver supports any storage backend ? 
In my enterprise, we use IBM SVC via fibre channel in openstack hypervisors.
Do cinder +cinder-docker-driver abstract the storage backend ?

Thanks for your help !

**Comment by john-griffith** [comment]
I haven't written connectors for anything other than iSCSI.  You might be interested in:
  https://github.com/openstack/fuxi

That uses the the standard OS Brick modules so you'll probably have support.

**Comment by j-griffith** [comment]
Closing this as far as the client issue, feel free to open a ER for the non-iscsi connectors.
