### ISSUE TITLE
question

### ISSUE THREAD

**Issue by timchenxiaoyu** [j-griffith/cinder-docker-driver#4]
after we crate volume,how to attch volume to my containers?

**Comment by j-griffith** [comment]
Hi timchenxiaoyu,

If you pre-created the volume (ie "docker volume create....") then you can just reference the name of the volume in your docker run command like you do with standard volume mappings.  Let's say for example you did:
`docker volume create --d solidfire --name foo`

Then when you launch your container you map the volume using the -v arg:
`docker run -v foo:/mountPointInsideContainer ubuntu bash`

Note you can also do it all in one shot:
`docker run --volume-driver solidfire -v foo:/mountPointInsidecontainer ubuntu bash`

If the volume doesn't exist already the docker driver will create it for you.

**Comment by timchenxiaoyu** [comment]
thanks for you reply,as we konw the cinder support many storage,for example,lvm,the docker monut to storage through iscs?

**Comment by j-griffith** [comment]
Currently this plugin just handles iSCSI.  It pull the information from the provider_info field from Cinder and uses that to attach, partition, format and finally mount the volume.
