### ISSUE TITLE
Is there any way we can resize volumes ?

### ISSUE THREAD

**Issue by thisismsreddy** [j-griffith/cinder-docker-driver#7]
As cinder allow to resize the volumes can we do that form this driver ? 
Exp - 
```
  $ docker volume update "name_of_the_volume " size = 20 
```

**Comment by j-griffith** [comment]
Hi,
So currently there really isn't a way to do that from the Docker Volume API.  One of the great things about Dockers Volume API IMO is that it's very basic, the only commands available from the API are:
Commands:
  create      Create a volume
  inspect     Display detailed information on one or more volumes
  ls          List volumes
  prune       Remove all unused volumes
  rm          Remove one or more volumes

That all being said, you *could* use Cinder to perform an extend.  Same Cinder rules apply about resizing an in-use volume etc, but it will allow you to perform the resize.  The Docker db should get updated on the next list/get call, but I haven't looked at that to verify.

**Comment by thisismsreddy** [comment]
Hey @j-griffith 
I've tried that , it's not updating docker database , I've created a volume using driver and resize that in cinder , but it still showing same size when I was created in docker inspect . 
Thanks
